spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TaskFlow
    username: root
    password: Alex552380
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: plannerwebsite23@gmail.com
    password: whsvdsxwxqsaxfdv
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.gmail.com
          auth: true
          starttls:
            enable: true
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath*:/init.sql
#      data-locations: classpath*:/data.sql

#server:
#  servlet:
#    context-path: /api

app:
  jwtSecret: MegaLargeSigningSecretKeyForDemoApplicationMegaLargeSigningSecretKeyForDemoApplication
  jwtExpirationMs: 86400000
